import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:zona_hub/src/models/user_model.dart';

class UserService {
  final CollectionReference usersRef =
      FirebaseFirestore.instance.collection('Users');

  Future<User> getUserDataFromDocRef(DocumentReference userRef) async {
    DocumentSnapshot userSnapshot = await userRef.get();
    return User.fromJson(userSnapshot.data() as Map<String, dynamic>);
  }

  // create user with an autogenerated id
  Future<void> createUser(User user) async {
    await usersRef.add(user.toJson());
  }

  // update user
  Future<void> updateUser(User user) async {
    await usersRef.doc(user.id).update(user.toJson());
  }

  // delete user
  Future<void> deleteUser(String id) async {
    await usersRef.doc(id).delete();
  }
}
