// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3CkaB4rIL6-T4kLra5sW6AkJ8NenCvPA',
    appId: '1:448365421824:web:ed651ff801baf62ee3ffe5',
    messagingSenderId: '448365421824',
    projectId: 'zonahub-b021c',
    authDomain: 'zonahub-b021c.firebaseapp.com',
    storageBucket: 'zonahub-b021c.appspot.com',
    measurementId: 'G-1F3PSNPH09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPjKAaREzwsEik2rHqYFdb-zncJO7XgRc',
    appId: '1:448365421824:android:c85e95dad97191c7e3ffe5',
    messagingSenderId: '448365421824',
    projectId: 'zonahub-b021c',
    storageBucket: 'zonahub-b021c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARzx5rBwLg28biU0MyxDd8d8G0Tmab4W8',
    appId: '1:448365421824:ios:8574df9be7318a61e3ffe5',
    messagingSenderId: '448365421824',
    projectId: 'zonahub-b021c',
    storageBucket: 'zonahub-b021c.appspot.com',
    iosClientId: '448365421824-k16lssktnobhd4mmue6jpn21q8r9c0r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zonaHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARzx5rBwLg28biU0MyxDd8d8G0Tmab4W8',
    appId: '1:448365421824:ios:8574df9be7318a61e3ffe5',
    messagingSenderId: '448365421824',
    projectId: 'zonahub-b021c',
    storageBucket: 'zonahub-b021c.appspot.com',
    iosClientId: '448365421824-k16lssktnobhd4mmue6jpn21q8r9c0r4.apps.googleusercontent.com',
    iosBundleId: 'com.example.zonaHub',
  );
}
